name: Checks and unit tests
on:
    pull_request:
        branches: [main]

env:
    CI: true
    AI_GIFTS_API_URL: http://localhost:3000
    FREE_CURRENCY_API_KEY: ${{ secrets.FREE_CURRENCY_API_KEY }}
    DATABASE_URL: postgres://postgres:password@localhost:5432/test
    DATABASE_URL_UNPOOLED: postgres://postgres:password@localhost:5432/test
    OPENAI_API_KEY: foo
    OPENAI_ORG_ID: foo
    PRINTIFY_API_TOKEN: ${{secrets.PRINTIFY_API_TOKEN}}
    SHOP_ID: foo
    STRIPE_SECRET_KEY: foo
    RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.11"
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Run lint check
              run: npm run lint:check
            - name: Run prettier check
              run: npm run fmt:check
            - name: npm build
              run: npm run build

    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.11"
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Run unit tests
              run: npm run test:ci
